routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/admin', function () {
    return view('admin.admin');
});

Route::get('/', function () {
    return view('layouts.master');
});

// ROUTE ADMIN 
Route::resource('admin', 'AdminController');
Route::get('/admin', 'AdminController@index')->name('admin');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/admin/store', 'AdminController@store')->name('add_admin');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/admin/update/{admin}', 'AdminController@update')->name('update_admin');
Route::delete('/admin/delete/{admin}', 'AdminController@destroy')->name('delete_admin');

//ROUTE FAQ
Route::resource('faq', 'FaqController');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/create', 'FaqController@create')->name('form_faq');
Route::post('/faq/store', 'FaqController@store')->name('add_faq');
Route::get('/faq/edit/{faq}', 'FaqController@edit')->name('edit_faq');
Route::put('/faq/update/{faq}', 'FaqController@update')->name('update_faq');
Route::delete('/faq/delete/{faq}', 'FaqController@destroy')->name('delete_faq');

//ROUTE VISION
Route::resource('vision', 'VisionController');
Route::get('/vision', 'VisionController@index')->name('vision');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/vision/store', 'VisionController@store')->name('add_vision');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/vision/update/{vision}', 'VisionController@update')->name('update_vision');
Route::delete('/vision/delete/{vision}', 'VisionController@destroy')->name('delete_vision');

//ROUTE MISSION
Route::resource('mission', 'MissionController');
Route::get('/mission', 'MissionController@index')->name('mission');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/mission/update/{mission}', 'MissionController@update')->name('update_mission');
Route::delete('/mission/delete/{mission}', 'MissionController@destroy')->name('delete_mission');

//ROUTE ADVANTAGE
Route::resource('advantage', 'AdvantageController');
Route::get('/advantage', 'AdvantageController@index')->name('advantage');
Route::get('/advantage/create', 'AdvantageController@create')->name('form_advantage');
Route::post('/advantage/store', 'AdvantageController@store')->name('add_advantage');
Route::get('/advantage/edit/{advantage}', 'AdvantageController@edit')->name('edit_advantage');
Route::put('/advantage/update/{advantage}', 'AdvantageController@update')->name('update_advantage');
Route::delete('/advantage/delete/{advantage}', 'AdvantageController@destroy')->name('delete_advantage');

//ROUTE FEATURE
Route::resource('feature', 'FeatureController');
Route::get('/feature', 'FeatureController@index')->name('feature');
Route::get('/feature/create', 'FeatureController@create')->name('form_feature');
Route::post('/feature/store', 'FeatureController@store')->name('add_feature');
Route::get('/feature/edit/{feature}', 'FeatureController@edit')->name('edit_feature');
Route::put('/feature/update/{feature}', 'FeatureController@update')->name('update_feature');
Route::delete('/feature/delete/{feature}', 'FeatureController@destroy')->name('delete_feature');

//ROUTE TESTIMONIAL
Route::resource('testimonial', 'TestimonialController');
Route::get('/testimonial', 'TestimonialController@index')->name('testimonial');
Route::get('/testimonial/create', 'TestimonialController@create')->name('form_testimonial');
Route::post('/testimonial/store', 'TestimonialController@store')->name('add_testimonial');
Route::get('/testimonial/edit/{testimonial}', 'TestimonialController@edit')->name('edit_testimonial');
Route::put('/testimonial/update/{testimonial}', 'TestimonialController@update')->name('update_testimonial');
Route::delete('/testimonial/delete/{testimonial}', 'TestimonialController@destroy')->name('delete_testimonial');

//ROUTE MESSAGES
Route::resource('message', 'MessageController');
Route::get('/message', 'MessageController@index')->name('message');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/message/update/{message}', 'MessageController@update')->name('update_message');
Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

//ROUTE SITES
Route::resource('site', 'SiteController');
// Route::get('/site', 'SiteController@index')->name('site');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/site/edit', 'SiteController@edit')->name('edit_site');
Route::put('/site/update/1', 'SiteController@update')->name('update_site');
// Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

// ROUTE PRODUCT 
Route::resource('product', 'ProductController');
Route::get('/product', 'ProductController@index')->name('product');
// Route::get('/product/create', 'ProductController@create');
Route::post('/product/store', 'ProductController@store')->name('add_product');
// Route::get('/product/edit/{product}', 'ProductController@edit')->name('edit_product');
Route::put('/product/update/{product}', 'ProductController@update')->name('update_product');
Route::delete('/product/delete/{product}', 'ProductController@destroy')->name('delete_product');

// AUTH
Auth::routes(['register' => false]);

// ROUTE LOGIN
Route::prefix('admins')->group(function(){
    Route::get('/login', 'Auth\AdminAuthController@getLogin')->name('admin.login');
    Route::post('/login', 'Auth\AdminAuthController@postLogin')->name('admin.login.submit');
  });

// ROUTE LOGOUT
Route::post('/logout', 'Auth\AdminAuthController@postLogout')->name('master.submit');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use softDeletes;

    protected $table = 'dashboard.products';

    protected $fillable = [
        'name', 'description', 'image', 'admin_id',
    ];

    public function admin()
    {
        return $this->belongsTo('App\Models\Admin');
    }

    public function product_fus()
    {
        return $this->hasMany('App\Models\Product_Fu');
    }

    public function product_features()
    {
        return $this->belongsToMany('App\Models\Product_Feature');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProduct;
use App\Http\Requests\UpdateProduct;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Gate;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $products = Product::all();
        return view('product.product', ['product' => $products]);
    }

    public function create()
    {
        return view('add_product');
    }
    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->only('admin_id', 'name', 'description', 'image');
        $data['admin_id'] = Auth::id();

        if ($request->has('image')){
            $path = $request->file('image')->store('public/images');
            $data['image'] = $path;
        }

        $product = Product::create($data);
        return redirect()->route('product');
    }

    public function edit(UpdateProduct $request, Product $product)
    {
        return view('update_product', compact('products'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Product $product)
    {
        $data = $request->only('admin_id', 'name', 'description', 'image');
        $data['admin_id'] = Auth::id();

        if ($request->has('image')){
            Storage::delete($product->image);
            $path = $request->file('image')->store('public/images');
            $data['image'] = $path;
        }

        $product->update($data);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request)
    {
        // dd($request);
        $product = Product::findOrFail($request->id);
        $product->delete();
        return back();
    }
}

resources/views/product/product.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Product
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Data Produk</h1>
    </div>
    <div class="section-body">
      <div class="row">
          <div class="col-md-12 col-lg-12">
              <div class="card">
                  <div class="card-header">
                    <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                      Tambah Produk
                    </button>
                    <div class="card-header-form ml-auto">
                      <form method="post" action="">
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="card-body">
                      <div class="table-responsive">                    
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Produk
                          </button> -->
                          <table class="table table-hover table-striped table-bordered ">
                          <thead>
                              <tr>
                                  <th scope="col" class="text-center">No</th>
                                  <th scope="col" class="text-center">Nama Produk</th>
                                  <!-- <th scope="col" class="text-center">Fitur</th> -->
                                  <th scope="col" class="text-center">Deskripsi</th>
                                  <th scope="col" class="text-center">Foto</th>
                                  <th scope="col" class="text-center">Updated At</th>
                                  <th scope="col" class="text-center">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @foreach($product as $key=>$prod)
                          <tr>
                              <td class="text-center">{{$key+1}}</td>
                              <td class="text-center">{{$prod->name}}</td>
                              <!-- <td class="text-center">{{$prod->fitur}}</td> -->
                              <td class="text-center">{{$prod->description}}</td>
                              <td class="text-center">
                                <?php $img_name = substr($prod->image, 13);?>
                                <img src="{{ asset('/storage/images').$img_name}}" alt="" title="" style="width: 100px; height: 100px;">
                              </td>
                              <td class="text-center">{{$prod->updated_at}}</td>
                              <td class="text-center">
                                  <button class="btn btn-sm" data-toggle="modal" data-target="#editModal" data-name="{{$prod->name}}" data-description="{{$prod->description}}" data-image="{{$prod->image}}" data-id="{{$prod->id}}">
                                    <img src="{{ asset('/assets/img/icon/icon-edit.png') }}">
                                  </button>
                                  <button class="btn btn-sm" data-id="{{$prod->id}}" data-toggle="modal" data-target="#deleteModal">
                                    <img src="{{ asset('/assets/img/icon/icon-delete.png') }}">
                                  </button>
                              </td>
                          </tr>
                          @endforeach
                          </tbody>
                      </table>
                     </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
</section>


<!-- Modal Add Data -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModalLabel">Tambah Data Produk</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('add_product') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label>Nama Produk</label>
                        <input type="text" name="name" id="name" placeholder="Nama Produk" class="form-control">
                    </div>
                    <!-- <div class="form-group">
                        <label>Fitur</label>
                        <input type="text" name="fitur" id="fitur" placeholder="Fitur" class="form-control">
                    </div> -->
                    <div class="form-group">
                        <label>Deskripsi</label>
                        <textarea type="text" name="description" id="description" placeholder="Deskripsi" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Foto</label>
                        <input type="file" name="image" id="image" class="form-control-file">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Tambah Data</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Data Produk</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="edit_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('put')}} <!-- cek change method -->
        <input type="hidden" name="id" id="id" value="">
            <div class="form-group">
            <label for="nama">Nama</label>
                <input type="text" class="form-control" name="name" id="name" value="">
            </div>
            <div class="form-group">
                <label for="description">Deskripsi</label>
                <textarea type="text" class="form-control" name="description" id="description" value=""></textarea>
            </div>
            <div class="form-group">
                <label>Foto</label>
                <input type="file" name="image" id="image" class="form-control-file" value="">
            </div>     
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Data Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="delete_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('delete')}}
      <div class="modal-body">
      <input type="hidden" name="id" id="id" value="">
        <p>Apakah anda yakin akan menghapus data ini?</p>
      </div>
      <div class="modal-footer">        
        <button type="submit" class="btn btn-primary">Ya</button>        
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Tidak</button>
      </div>
      </form>
    </div>
  </div>
</div>

@endsection

@section('scripts')
<script>
  $('#editModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var name = button.data('name')
    var description = button.data('description')
    var image = button.data('image')
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('product.update', '') }}/${id}`; // generate url
    $('#edit_form').attr('action', url); // set edit_form action attribute  

    modal.find('.modal-body #name').val(name);
    modal.find('.modal-body #description').val(description);
    modal.find('.modal-body #image').val(image);
    modal.find('.modal-body #id').val(id);
  })

  $('#deleteModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('product.destroy', '') }}/${id}`; // generate url
    $('#delete_form').attr('action', url); // set edit_form action attribute

    modal.find('.modal-body #id').val(id);
  })

</script>
@endsection