routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/admin', function () {
    return view('admin.admin');
});

Route::get('/', function () {
    return view('layouts.master');
});

// ROUTE ADMIN 
Route::resource('admin', 'AdminController');
Route::get('/admin', 'AdminController@index')->name('admin');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/admin/store', 'AdminController@store')->name('add_admin');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/admin/update/{admin}', 'AdminController@update')->name('update_admin');
Route::delete('/admin/delete/{admin}', 'AdminController@destroy')->name('delete_admin');

//ROUTE FAQ
Route::resource('faq', 'FaqController');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/create', 'FaqController@create')->name('form_faq');
Route::post('/faq/store', 'FaqController@store')->name('add_faq');
Route::get('/faq/edit/{faq}', 'FaqController@edit')->name('edit_faq');
Route::put('/faq/update/{faq}', 'FaqController@update')->name('update_faq');
Route::delete('/faq/delete/{faq}', 'FaqController@destroy')->name('delete_faq');

//ROUTE VISION
Route::resource('vision', 'VisionController');
Route::get('/vision', 'VisionController@index')->name('vision');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/vision/store', 'VisionController@store')->name('add_vision');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/vision/update/{vision}', 'VisionController@update')->name('update_vision');
Route::delete('/vision/delete/{vision}', 'VisionController@destroy')->name('delete_vision');

//ROUTE MISSION
Route::resource('mission', 'MissionController');
Route::get('/mission', 'MissionController@index')->name('mission');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/mission/update/{mission}', 'MissionController@update')->name('update_mission');
Route::delete('/mission/delete/{mission}', 'MissionController@destroy')->name('delete_mission');

//ROUTE ADVANTAGE
Route::resource('advantage', 'AdvantageController');
Route::get('/advantage', 'AdvantageController@index')->name('advantage');
Route::get('/advantage/create', 'AdvantageController@create')->name('form_advantage');
Route::post('/advantage/store', 'AdvantageController@store')->name('add_advantage');
Route::get('/advantage/edit/{advantage}', 'AdvantageController@edit')->name('edit_advantage');
Route::put('/advantage/update/{advantage}', 'AdvantageController@update')->name('update_advantage');
Route::delete('/advantage/delete/{advantage}', 'AdvantageController@destroy')->name('delete_advantage');

//ROUTE FEATURE
Route::resource('feature', 'FeatureController');
Route::get('/feature', 'FeatureController@index')->name('feature');
Route::get('/feature/create', 'FeatureController@create')->name('form_feature');
Route::post('/feature/store', 'FeatureController@store')->name('add_feature');
Route::get('/feature/edit/{feature}', 'FeatureController@edit')->name('edit_feature');
Route::put('/feature/update/{feature}', 'FeatureController@update')->name('update_feature');
Route::delete('/feature/delete/{feature}', 'FeatureController@destroy')->name('delete_feature');

//ROUTE TESTIMONIAL
Route::resource('testimonial', 'TestimonialController');
Route::get('/testimonial', 'TestimonialController@index')->name('testimonial');
Route::get('/testimonial/create', 'TestimonialController@create')->name('form_testimonial');
Route::post('/testimonial/store', 'TestimonialController@store')->name('add_testimonial');
Route::get('/testimonial/edit/{testimonial}', 'TestimonialController@edit')->name('edit_testimonial');
Route::put('/testimonial/update/{testimonial}', 'TestimonialController@update')->name('update_testimonial');
Route::delete('/testimonial/delete/{testimonial}', 'TestimonialController@destroy')->name('delete_testimonial');

//ROUTE MESSAGES
Route::resource('message', 'MessageController');
Route::get('/message', 'MessageController@index')->name('message');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/message/update/{message}', 'MessageController@update')->name('update_message');
Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

//ROUTE SITES
Route::resource('site', 'SiteController');
// Route::get('/site', 'SiteController@index')->name('site');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/site/edit', 'SiteController@edit')->name('edit_site');
Route::put('/site/update/1', 'SiteController@update')->name('update_site');
// Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

// ROUTE PRODUCT 
Route::resource('product', 'ProductController');
Route::get('/product', 'ProductController@index')->name('product');
// Route::get('/product/create', 'ProductController@create');
Route::post('/product/store', 'ProductController@store')->name('add_product');
// Route::get('/product/edit/{product}', 'ProductController@edit')->name('edit_product');
Route::put('/product/update/{product}', 'ProductController@update')->name('update_product');
Route::delete('/product/delete/{product}', 'ProductController@destroy')->name('delete_product');

// AUTH
Auth::routes(['register' => false]);

// ROUTE LOGIN
Route::prefix('admins')->group(function(){
    Route::get('/login', 'Auth\AdminAuthController@getLogin')->name('admin.login');
    Route::post('/login', 'Auth\AdminAuthController@postLogin')->name('admin.login.submit');
  });

// ROUTE LOGOUT
Route::post('/logout', 'Auth\AdminAuthController@postLogout')->name('master.submit');

resources/views/admin/admin.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Admin
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Admin</h1>
    </div>
    <div class="section-body">
      <div class="row">
          <div class="col-md-12 col-lg-12">
              <div class="card">
                <div class="card-header">
                    <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                      Tambah Data Admin
                    </button>
                    <div class="card-header-form ml-auto">
                      <form method="GET" action="{{ route('admin') }}">
                        <div class="input-group">
                          <input type="text" class="form-control" id="search" name="search" placeholder="Search by name">
                          <div class="input-group-btn">
                            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                </div>
                  <div class="card-body">
                      <table class="table table-striped">
                          <table class="table table-hover table-striped table-bordered ">
                          <thead>
                              <tr>
                                  <th scope="col" class="text-center">No</th>
                                  <th scope="col" class="text-center">Name</th>
                                  <th scope="col" class="text-center">Username</th>
                                  <th scope="col" class="text-center">Email</th>
                                  <th scope="col" class="text-center">Updated At</th>
                                  <th scope="col" class="text-center">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @foreach($admin as $index => $adm)
                          <tr>
                              <td class="text-center">{{$index+1}}</td>
                              <td class="text-center">{{$adm->name}}</td>
                              <td class="text-center">{{$adm->username}}</td>
                              <td class="text-center">{{$adm->email}}</td>
                              <td class="text-center">{{$adm->updated_at}}</td>
                              <td class="text-center">
                                  <button class="btn btn-sm" data-name="{{$adm->name}}" data-username="{{$adm->username}}" data-email="{{$adm->email}}" data-id="{{$adm->id}}" data-toggle="modal" data-target="#editModal">
                                    <img src="{{ asset('/assets/img/icon/icon-edit.png') }}">
                                  </button>
                                  <button class="btn btn-sm" data-id="{{$adm->id}}" data-toggle="modal" data-target="#deleteModal">
                                    <img src="{{ asset('/assets/img/icon/icon-delete.png') }}">
                                  </button>
                              </td>
                          </tr>
                          @endforeach
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
    </div>
</section>

<!-- Modal Add Data -->
<div class="modal fade" id="addModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addModalLabel">Tambah Data Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ route('add_admin') }}" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="nama">Nama</label>
                <input type="text" class="form-control" name="name" id="nama" placeholder="Nama" required>
            </div>
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" placeholder="Username" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>        
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Cancel</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Data Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="edit_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('put')}} <!-- cek change method -->
        <input type="hidden" name="id" id="id" value="">
            <div class="form-group">
            <label for="nama">Nama</label>
                <input type="text" class="form-control" name="name" id="name" value="">
            </div>
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" value="">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" value="">
            </div>      
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Data Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="delete_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('delete')}}
      <div class="modal-body">
      <input type="hidden" name="id" id="id" value="">
        <p>Apakah anda yakin akan menghapus data ini?</p>
      </div>
      <div class="modal-footer">        
        <button type="submit" class="btn btn-primary">Ya</button>        
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Tidak</button>
      </div>
      </form>
    </div>
  </div>
</div>

@endsection

@section('scripts')
<script>
  $('#editModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var name = button.data('name')
    var username = button.data('username')
    var email = button.data('email')
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('admin.update', '') }}/${id}`; // generate url
    $('#edit_form').attr('action', url); // set edit_form action attribute  

    modal.find('.modal-body #name').val(name);
    modal.find('.modal-body #username').val(username);
    modal.find('.modal-body #email').val(email);
    modal.find('.modal-body #id').val(id);
  })

  $('#deleteModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('admin.destroy', '') }}/${id}`; // generate url
    $('#delete_form').attr('action', url); // set edit_form action attribute

    modal.find('.modal-body #id').val(id);
  })

</script>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.header')

@section('content')
<section class="section">
    <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="login-brand">
              <img src="../assets/img/nusantaraGPS.png" alt="logo" width="200">
            </div>

            <div class="card card-primary">
              <div class="card-header"><h4>Login Admin</h4></div>

              <div class="card-body">
                <form method="POST" action="{{ route('admin.login.submit')}}" class="needs-validation" novalidate="">
                @csrf
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{ old('username') }}" required autocomplete="username" autofocus>

                    @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    
                  </div>
                  
                  <div class="form-group">
                    <div class="d-block">
                    	<label for="password" class="control-label">Password</label>
                      <div class="float-right">
                        @if (Route::has('password.request'))
                        <a href="{{ route('password.request') }}" class="text-small">
                          Forgot Password?
                        </a>
                        @endif
                      </div>
                    </div>
                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" tabindex="2" required>
                    
                    @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                  </div>

                  <div class="form-group">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me" {{ old('remember') ? 'checked' : '' }}>
                      <label class="custom-control-label" for="remember-me">Remember Me</label>
                    </div>
                  </div>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                      Login
                    </button>
                  </div>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>
@endsection