routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/admin', function () {
    return view('admin.admin');
});

Route::get('/', function () {
    return view('layouts.master');
});

// ROUTE ADMIN 
Route::resource('admin', 'AdminController');
Route::get('/admin', 'AdminController@index')->name('admin');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/admin/store', 'AdminController@store')->name('add_admin');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/admin/update/{admin}', 'AdminController@update')->name('update_admin');
Route::delete('/admin/delete/{admin}', 'AdminController@destroy')->name('delete_admin');

//ROUTE FAQ
Route::resource('faq', 'FaqController');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/create', 'FaqController@create')->name('form_faq');
Route::post('/faq/store', 'FaqController@store')->name('add_faq');
Route::get('/faq/edit/{faq}', 'FaqController@edit')->name('edit_faq');
Route::put('/faq/update/{faq}', 'FaqController@update')->name('update_faq');
Route::delete('/faq/delete/{faq}', 'FaqController@destroy')->name('delete_faq');

//ROUTE VISION
Route::resource('vision', 'VisionController');
Route::get('/vision', 'VisionController@index')->name('vision');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/vision/store', 'VisionController@store')->name('add_vision');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/vision/update/{vision}', 'VisionController@update')->name('update_vision');
Route::delete('/vision/delete/{vision}', 'VisionController@destroy')->name('delete_vision');

//ROUTE MISSION
Route::resource('mission', 'MissionController');
Route::get('/mission', 'MissionController@index')->name('mission');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/mission/update/{mission}', 'MissionController@update')->name('update_mission');
Route::delete('/mission/delete/{mission}', 'MissionController@destroy')->name('delete_mission');

//ROUTE ADVANTAGE
Route::resource('advantage', 'AdvantageController');
Route::get('/advantage', 'AdvantageController@index')->name('advantage');
Route::get('/advantage/create', 'AdvantageController@create')->name('form_advantage');
Route::post('/advantage/store', 'AdvantageController@store')->name('add_advantage');
Route::get('/advantage/edit/{advantage}', 'AdvantageController@edit')->name('edit_advantage');
Route::put('/advantage/update/{advantage}', 'AdvantageController@update')->name('update_advantage');
Route::delete('/advantage/delete/{advantage}', 'AdvantageController@destroy')->name('delete_advantage');

//ROUTE FEATURE
Route::resource('feature', 'FeatureController');
Route::get('/feature', 'FeatureController@index')->name('feature');
Route::get('/feature/create', 'FeatureController@create')->name('form_feature');
Route::post('/feature/store', 'FeatureController@store')->name('add_feature');
Route::get('/feature/edit/{feature}', 'FeatureController@edit')->name('edit_feature');
Route::put('/feature/update/{feature}', 'FeatureController@update')->name('update_feature');
Route::delete('/feature/delete/{feature}', 'FeatureController@destroy')->name('delete_feature');

//ROUTE TESTIMONIAL
Route::resource('testimonial', 'TestimonialController');
Route::get('/testimonial', 'TestimonialController@index')->name('testimonial');
Route::get('/testimonial/create', 'TestimonialController@create')->name('form_testimonial');
Route::post('/testimonial/store', 'TestimonialController@store')->name('add_testimonial');
Route::get('/testimonial/edit/{testimonial}', 'TestimonialController@edit')->name('edit_testimonial');
Route::put('/testimonial/update/{testimonial}', 'TestimonialController@update')->name('update_testimonial');
Route::delete('/testimonial/delete/{testimonial}', 'TestimonialController@destroy')->name('delete_testimonial');

//ROUTE MESSAGES
Route::resource('message', 'MessageController');
Route::get('/message', 'MessageController@index')->name('message');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/message/update/{message}', 'MessageController@update')->name('update_message');
Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

//ROUTE SITES
Route::resource('site', 'SiteController');
// Route::get('/site', 'SiteController@index')->name('site');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/site/edit', 'SiteController@edit')->name('edit_site');
Route::put('/site/update/1', 'SiteController@update')->name('update_site');
// Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

// ROUTE PRODUCT 
Route::resource('product', 'ProductController');
Route::get('/product', 'ProductController@index')->name('product');
// Route::get('/product/create', 'ProductController@create');
Route::post('/product/store', 'ProductController@store')->name('add_product');
// Route::get('/product/edit/{product}', 'ProductController@edit')->name('edit_product');
Route::put('/product/update/{product}', 'ProductController@update')->name('update_product');
Route::delete('/product/delete/{product}', 'ProductController@destroy')->name('delete_product');

// AUTH
Auth::routes(['register' => false]);

// ROUTE LOGIN
Route::prefix('admins')->group(function(){
    Route::get('/login', 'Auth\AdminAuthController@getLogin')->name('admin.login');
    Route::post('/login', 'Auth\AdminAuthController@postLogin')->name('admin.login.submit');
  });

// ROUTE LOGOUT
Route::post('/logout', 'Auth\AdminAuthController@postLogout')->name('master.submit');

resources/views/information/faq.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | FAQ
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Data Frequently Asked Question (FAQ)</h1>
    </div>
    <div class="section-body">
      <div class="row">
          <div class="col-md-12 col-lg-12">
              <div class="card">
                  <div class="card-header">
                    <a href="{{ route('form_faq') }}" class="btn btn-primary my-4">
                      Tambah FAQ
                    </a>
                    <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                      Tambah FAQ
                    </button> -->
                    <div class="card-header-form ml-auto">
                      <form method="get" action="{{ route('faq') }}">
                        <div class="input-group">
                          <input type="text" class="form-control" name="search" placeholder="Search by pertanyaan">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-striped table-bordered">                    
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah FAQ
                          </button> -->
                          <thead>
                              <tr>
                                  <th scope="col" class="text-center">No</th>
                                  <th scope="col" class="text-center">Pertanyaan</th>
                                  <th scope="col" class="text-center">Jawaban</th>
                                  <th scope="col" class="text-center">Updated At</th>
                                  <th scope="col" class="text-center">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @foreach($faq as $index=>$f)
                          <tr>
                              <td class="text-center">{{$index+1}}</td>
                              <td class="text-center">{{$f->title}}</td>
                              <td class="text-center">{{$f->content}}</td>
                              <td class="text-center">{{$f->updated_at}}</td>
                              <td class="text-center">
                              <div class="d-inline">
                                 <button class="btn btn-sm" data-id="{{$f->id}}" data-title="{{$f->title}}" data-content="{{$f->content}}"
                                  data-admin_id="{{$f->admin_id}}" data-toggle="modal" data-updated_at="{{$f->updated_at}}" data-target="#detailModal">
                                    <img src="{{ asset('/assets/img/icon/icon-detail.png') }}">
                                  </button>
                                  <a href="{{ route('edit_faq', $f->id) }}" class="btn btn-sm" data-title="{{$f->title}}" data-content="{{$f->content}}" data-id="{{$f->id}}">
                                    <img src="{{ asset('/assets/img/icon/icon-edit.png') }}">
                                  </a>
                                  <button class="btn btn-sm" data-id="{{$f->id}}" data-toggle="modal" data-target="#deleteModal">
                                    <img src="{{ asset('/assets/img/icon/icon-delete.png') }}">
                                  </button> 
                              </div>
                                                                   
                              </td>
                          </tr>
                          @endforeach
                          </tbody>
                      </table>
                    </div>
                      
                  </div>
              </div>
          </div>
      </div>
    </div>
</section>

<!-- Modal Detail Data -->
<div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Detail Data FAQ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="detail_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
            {{csrf_field()}}
            {{method_field('put')}} <!-- cek change method -->
                <div class="modal-body">
                    <input type="hidden" name="id" value="" id="id">
                    <div class="form-group">
                        <label>Pertanyaan</label>
                        <input type="text" name="title" id="title" value=""  class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <label>Jawaban</label>
                        <textarea name="content" id="content" value="" class="form-control" readonly></textarea>
                    </div>
                    <div class="form-group">
                        <label>Updated At</label>
                        <input type="text" name="updated_at" id="updated_at" value="" class="form-control" readonly>
                    </div>
                </div>            
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Data FAQ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                <form id="edit_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
                {{ csrf_field() }}
                {{ method_field('put') }}<!-- cek change method -->
                    <input type="hidden" name="id" value="" id="id">
                    <div class="form-group">
                        <label>Pertanyaan</label>
                        <input type="text" name="title" id="title" value="" placeholder="Pertanyaan"  class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Jawaban</label>
                        <input type="text" name="content" id="content" value="" placeholder="Jawaban" class="form-control">
                    </div>
                </div>            
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Edit Data</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="deleteModalLabel">Konfirmasi Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="delete_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
                {{ csrf_field() }}
                {{ method_field('delete') }}
                <div class="modal-body">
                    <input type="hidden" name="id" value="" id="id">
                    <p class="text-area">
                        Apakah anda yakin akan menghapus data ini?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Iya, Hapus </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
  $('#editModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var title = button.data('title')
    var content = button.data('content')
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('faq.update', '') }}/${id}`; // generate url
    $('#edit_form').attr('action', url); // set edit_form action attribute  

    modal.find('.modal-body #title').val(title);
    modal.find('.modal-body #content').val(content);
    modal.find('.modal-body #id').val(id);
  })

  $('#deleteModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('faq.destroy', '') }}/${id}`; // generate url
    $('#delete_form').attr('action', url); // set edit_form action attribute

    modal.find('.modal-body #id').val(id);
  })

  $('#detailModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var title = button.data('title')
    var content = button.data('content')
    var admin_id = button.data('admin_id')
    var updated_at = button.data('updated_at')
    var id = button.data('id')
    var modal = $(this)

    modal.find('.modal-body #title').val(title);
    modal.find('.modal-body #content').val(content);
    modal.find('.modal-body #admin_id').val(admin_id);
    modal.find('.modal-body #updated_at').val(updated_at);
    modal.find('.modal-body #id').val(id);
  })

</script>
@endsection

resources/views/information/faq_edit.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Blog FAQ
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Edit Data FAQ</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Form Edit FAQ</h4>
                    </div>
                    <div class="card-body">
                    <form method="POST" action="{{ route('update_faq', $faq->id) }}" enctype=" multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('put') }}
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pertanyaan</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="title" id="title" placeholder="Pertanyaan" value="{{$faq->title}}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Jawaban</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea type="text" rows="14" name="content" id="content" placeholder="Deskripsi" value="" class="form-control">{{ $faq->content }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-primary">Edit Data</button>
                                <a href="{{ route('faq') }}" class="btn btn-secondary ml-2">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

@endsection

@section('scripts')

@endsection

resources/views/information/faq_form.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Blog FAQ
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Tambah Data FAQ</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Form Tambah FAQ</h4>
                    </div>
                    <div class="card-body">
                    <form method="POST" action="{{ route('add_faq') }}" enctype=" multipart/form-data">                    
                    {{ csrf_field() }}
                    {{ method_field('post') }}
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Pertanyaan</label>
                            <div class="col-sm-12 col-md-7">
                                <input type="text" name="title" id="title" placeholder="Pertanyaan" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="content">Jawaban</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea type="text" rows="14" name="content" id="content" placeholder="Jawaban" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-primary">Tambah Data</button>
                                <a href="{{ route('faq') }}" class="btn btn-secondary ml-2">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

@endsection

@section('scripts')

@endsection

resources/views/information/testimoni.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Testimoni
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Data Testimoni</h1>
    </div>
    <div class="section-body">
      <div class="row">
          <div class="col-md-12 col-lg-12">
              <div class="card">
                  <div class="card-header">
                    <a href="{{ route('form_testimonial') }}" class="btn btn-primary my-4">
                      Tambah Testimoni
                    </a>
                    <div class="card-header-form ml-auto">
                      <form method="get" action="{{ route('testimonial') }}">
                        <div class="input-group">
                          <input type="text" class="form-control" name="search" placeholder="Search by title">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="card-body">
                      <table class="table table-hover table-striped table-bordered">                    
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Data Keunggulan
                          </button> -->
                      <!-- <table class="table table-striped">                     -->
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Data Keunggulan
                          </button> -->
                          <!-- <table class="table table-hover table-striped table-bordered "> -->
                          <thead>
                              <tr>
                                  <th scope="col" class="text-center">No</th>
                                  <th scope="col" class="text-center">Posisi</th>
                                  <th scope="col" class="text-center">Konten</th>
                                  <th scope="col" class="text-center">Foto</th>
                                  <th scope="col" class="text-center">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @foreach($testimonial as $key=>$testi)
                          <tr>
                              <td class="text-center">{{$key+1}}</td>
                              <td class="text-center">{{$testi->position}}</td>
                              <td class="text-center">{{$testi->content}}</td>
                              <!-- <td class="text-center"><img src="{{URL::to('/storage/app/')}}{{$testi->image}}" style="width: 100px; height: 100px;"></td> -->
                              <!-- <td class="text-center"><img src="{{ url('/storage/app/'.$testi->image) }}" alt="" title=""></td> -->
                              <td class="text-center">
                                <?php $img_name = substr($testi->image, 13);?>
                                <img src="{{ asset('/storage/images').$img_name}}" alt="" title="" style="width: 100px; height: 100px;">
                              </td>
                              <td class="text-center">
                                  <a href="{{ route('edit_testimonial', $testi->id) }}" class="btn btn-sm" data-id="{{$testi->id}}" data-position="{{$testi->position}}" data-content="{{$testi->content}}" data-image="{{$testi->image}}">
                                    <img src="{{ asset('/assets/img/icon/icon-edit.png') }}">
                                  </a>
                                  <button class="btn btn-sm" data-id="{{$testi->id}}" data-toggle="modal" data-target="#deleteModal">
                                    <img src="{{ asset('/assets/img/icon/icon-delete.png') }}">
                                  </button>
                              </td>
                          </tr>
                          @endforeach
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
    </div>
</section>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Data Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="edit_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('put')}} <!-- cek change method -->
        <input type="hidden" name="id" id="id" value="">
            <div class="form-group">
            <label for="content">Posisi</label>
                <input type="text" class="form-control" name="position" id="position" value="">
            </div>
            <div class="form-group">
            <label for="content">Konten</label>
                <input type="text" class="form-control" name="content" id="content" value="">
            </div>
            <div class="form-group">
            <label for="content">Icon</label>
                <input type="file" class="form-control" name="image" id="image" class="form-control-file" value="">
            </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Edit Data</button>
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="deleteModalLabel">Konfirmasi Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="delete_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
                {{ csrf_field() }}
                {{ method_field('delete') }}
                <div class="modal-body">
                    <input type="hidden" name="id" value="" id="id">
                    <p class="text-area">
                        Apakah anda yakin akan menghapus data ini?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Iya, Hapus </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
  $('#editModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var admin_id = button.data('admin_id')
    var title = button.data('title')
    var description = button.data('description')
    var image = button.data('image')
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('testimonial.update', '') }}/${id}`; // generate url
    $('#edit_form').attr('action', url); // set edit_form action attribute  

    modal.find('.modal-body #admin_id').val(admin_id);
    modal.find('.modal-body #position').val(position);
    modal.find('.modal-body #content').val(content);
    modal.find('.modal-body #image').val(image);
  })

  $('#deleteModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('testimonial.destroy', '') }}/${id}`; // generate url
    $('#delete_form').attr('action', url); // set edit_form action attribute

    modal.find('.modal-body #id').val(id);
  })
</script>
@endsection