routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/admin', function () {
    return view('admin.admin');
});

Route::get('/', function () {
    return view('layouts.master');
});

// ROUTE ADMIN 
Route::resource('admin', 'AdminController');
Route::get('/admin', 'AdminController@index')->name('admin');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/admin/store', 'AdminController@store')->name('add_admin');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/admin/update/{admin}', 'AdminController@update')->name('update_admin');
Route::delete('/admin/delete/{admin}', 'AdminController@destroy')->name('delete_admin');

//ROUTE FAQ
Route::resource('faq', 'FaqController');
Route::get('/faq', 'FaqController@index')->name('faq');
Route::get('/faq/create', 'FaqController@create')->name('form_faq');
Route::post('/faq/store', 'FaqController@store')->name('add_faq');
Route::get('/faq/edit/{faq}', 'FaqController@edit')->name('edit_faq');
Route::put('/faq/update/{faq}', 'FaqController@update')->name('update_faq');
Route::delete('/faq/delete/{faq}', 'FaqController@destroy')->name('delete_faq');

//ROUTE VISION
Route::resource('vision', 'VisionController');
Route::get('/vision', 'VisionController@index')->name('vision');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/vision/store', 'VisionController@store')->name('add_vision');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/vision/update/{vision}', 'VisionController@update')->name('update_vision');
Route::delete('/vision/delete/{vision}', 'VisionController@destroy')->name('delete_vision');

//ROUTE MISSION
Route::resource('mission', 'MissionController');
Route::get('/mission', 'MissionController@index')->name('mission');
// Route::get('/admin/create', 'AdminController@create');
Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/mission/update/{mission}', 'MissionController@update')->name('update_mission');
Route::delete('/mission/delete/{mission}', 'MissionController@destroy')->name('delete_mission');

//ROUTE ADVANTAGE
Route::resource('advantage', 'AdvantageController');
Route::get('/advantage', 'AdvantageController@index')->name('advantage');
Route::get('/advantage/create', 'AdvantageController@create')->name('form_advantage');
Route::post('/advantage/store', 'AdvantageController@store')->name('add_advantage');
Route::get('/advantage/edit/{advantage}', 'AdvantageController@edit')->name('edit_advantage');
Route::put('/advantage/update/{advantage}', 'AdvantageController@update')->name('update_advantage');
Route::delete('/advantage/delete/{advantage}', 'AdvantageController@destroy')->name('delete_advantage');

//ROUTE FEATURE
Route::resource('feature', 'FeatureController');
Route::get('/feature', 'FeatureController@index')->name('feature');
Route::get('/feature/create', 'FeatureController@create')->name('form_feature');
Route::post('/feature/store', 'FeatureController@store')->name('add_feature');
Route::get('/feature/edit/{feature}', 'FeatureController@edit')->name('edit_feature');
Route::put('/feature/update/{feature}', 'FeatureController@update')->name('update_feature');
Route::delete('/feature/delete/{feature}', 'FeatureController@destroy')->name('delete_feature');

//ROUTE TESTIMONIAL
Route::resource('testimonial', 'TestimonialController');
Route::get('/testimonial', 'TestimonialController@index')->name('testimonial');
Route::get('/testimonial/create', 'TestimonialController@create')->name('form_testimonial');
Route::post('/testimonial/store', 'TestimonialController@store')->name('add_testimonial');
Route::get('/testimonial/edit/{testimonial}', 'TestimonialController@edit')->name('edit_testimonial');
Route::put('/testimonial/update/{testimonial}', 'TestimonialController@update')->name('update_testimonial');
Route::delete('/testimonial/delete/{testimonial}', 'TestimonialController@destroy')->name('delete_testimonial');

//ROUTE MESSAGES
Route::resource('message', 'MessageController');
Route::get('/message', 'MessageController@index')->name('message');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/admin/edit/{admin}', 'AdminController@edit')->name('edit_admin');
Route::put('/message/update/{message}', 'MessageController@update')->name('update_message');
Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

//ROUTE SITES
Route::resource('site', 'SiteController');
// Route::get('/site', 'SiteController@index')->name('site');
// Route::get('/admin/create', 'AdminController@create');
// Route::post('/mission/store', 'MissionController@store')->name('add_mission');
// Route::get('/site/edit', 'SiteController@edit')->name('edit_site');
Route::put('/site/update/1', 'SiteController@update')->name('update_site');
// Route::delete('/message/delete/{message}', 'MessageController@destroy')->name('delete_message');

// ROUTE PRODUCT 
Route::resource('product', 'ProductController');
Route::get('/product', 'ProductController@index')->name('product');
// Route::get('/product/create', 'ProductController@create');
Route::post('/product/store', 'ProductController@store')->name('add_product');
// Route::get('/product/edit/{product}', 'ProductController@edit')->name('edit_product');
Route::put('/product/update/{product}', 'ProductController@update')->name('update_product');
Route::delete('/product/delete/{product}', 'ProductController@destroy')->name('delete_product');

// AUTH
Auth::routes(['register' => false]);

// ROUTE LOGIN
Route::prefix('admins')->group(function(){
    Route::get('/login', 'Auth\AdminAuthController@getLogin')->name('admin.login');
    Route::post('/login', 'Auth\AdminAuthController@postLogin')->name('admin.login.submit');
  });

// ROUTE LOGOUT
Route::post('/logout', 'Auth\AdminAuthController@postLogout')->name('master.submit');

resources/views/pages/fitur.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Fitur
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Data Fitur</h1>
    </div>
    <div class="section-body">
      <div class="row">
          <div class="col-md-12 col-lg-12">
              <div class="card">
                  <div class="card-header">
                    <a href="{{ route('form_feature') }}" class="btn btn-primary my-4">
                      Tambah Fitur
                    </a>
                    <div class="card-header-form ml-auto">
                      <form method="get" action="{{ route('feature') }}">
                        <div class="input-group">
                          <input type="text" class="form-control" name="search" placeholder="Search by title">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="card-body">
                      <table class="table table-hover table-striped table-bordered">                    
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Data Keunggulan
                          </button> -->
                      <!-- <table class="table table-striped">                     -->
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Data Keunggulan
                          </button> -->
                          <!-- <table class="table table-hover table-striped table-bordered "> -->
                          <thead>
                              <tr>
                                  <th scope="col" class="text-center">No</th>
                                  <th scope="col" class="text-center">Judul</th>
                                  <th scope="col" class="text-center">Deskripsi</th>
                                  <th scope="col" class="text-center">Icon</th>
                                  <th scope="col" class="text-center">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @foreach($feature as $key=>$feat)
                          <tr>
                              <td class="text-center">{{$key+1}}</td>
                              <td class="text-center">{{$feat->title}}</td>
                              <td class="text-center">{{$feat->description}}</td>
                              <!-- <td class="text-center"><img src="{{URL::to('/storage/app/')}}{{$feat->image}}" style="width: 100px; height: 100px;"></td> -->
                              <!-- <td class="text-center"><img src="{{ url('/storage/app/'.$feat->image) }}" alt="" title=""></td> -->
                              <td class="text-center">
                                <?php $img_name = substr($feat->image, 13);?>
                                <img src="{{ asset('/storage/images').$img_name}}" alt="" title="" style="width: 100px; height: 100px;">
                              </td>
                              <td class="text-center">
                                  <a href="{{ route('edit_feature', $feat->id) }}" class="btn btn-sm" data-id="{{$feat->id}}" data-title="{{$feat->title}}" data-description="{{$feat->description}}" data-image="{{$feat->image}}">
                                    <img src="{{ asset('/assets/img/icon/icon-edit.png') }}">
                                  </a>
                                  <button class="btn btn-sm" data-id="{{$feat->id}}" data-toggle="modal" data-target="#deleteModal">
                                    <img src="{{ asset('/assets/img/icon/icon-delete.png') }}">
                                  </button>
                              </td>
                          </tr>
                          @endforeach
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
    </div>
</section>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Data Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="edit_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('put')}} <!-- cek change method -->
        <input type="hidden" name="id" id="id" value="">
            <div class="form-group">
            <label for="content">Judul</label>
                <input type="text" class="form-control" name="title" id="title" value="">
            </div>
            <div class="form-group">
            <label for="content">Deskripsi</label>
                <input type="text" class="form-control" name="description" id="description" value="">
            </div>
            <div class="form-group">
            <label for="content">Icon</label>
                <input type="file" class="form-control" name="image" id="image" class="form-control-file" value="">
            </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Edit Data</button>
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="deleteModalLabel">Konfirmasi Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="delete_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
                {{ csrf_field() }}
                {{ method_field('delete') }}
                <div class="modal-body">
                    <input type="hidden" name="id" value="" id="id">
                    <p class="text-area">
                        Apakah anda yakin akan menghapus data ini?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Iya, Hapus </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
  $('#editModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var admin_id = button.data('admin_id')
    var title = button.data('title')
    var description = button.data('description')
    var image = button.data('image')
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('feature.update', '') }}/${id}`; // generate url
    $('#edit_form').attr('action', url); // set edit_form action attribute  

    modal.find('.modal-body #admin_id').val(admin_id);
    modal.find('.modal-body #title').val(title);
    modal.find('.modal-body #description').val(description);
    modal.find('.modal-body #image').val(image);
  })

  $('#deleteModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('feature.destroy', '') }}/${id}`; // generate url
    $('#delete_form').attr('action', url); // set edit_form action attribute

    modal.find('.modal-body #id').val(id);
  })
</script>
@endsection

resources/views/pages/fitur_edit.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Keunggulan Post
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Tambah Data Fitur</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Form Tambah Data Fitur</h4>
                    </div>
                    <div class="card-body">
                    <form action="{{ route('update_feature', $feature->id) }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('put') }}
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul</label>
                            <div class="col-sm-12 col-md-7">
                            <input type="text" name="title" id="title" placeholder="Judul" class="form-control" value="{{ $feature->title }}">
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi</label>
                            <div class="col-sm-12 col-md-7">
                            <textarea type="text" name="description" id="description" placeholder="Deskripsi" class="form-control" value="">{{ $feature->description }}</textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Icon</label>
                            <div class="col-sm-12 col-md-7">
                                <div id="image-preview" class="image-preview">                            
                                    <?php $img_name = substr($feature->image, 13);?>
                                    <img src="{{ asset('/storage/images').$img_name}}" alt="" title="" style="width: 100px; height: 100px;">
                                    <input type="file" name="image" id="image" class="form-control-file" accept="image/png, image/jpeg">
                                    <!-- <input type="file" name="image" id="image"> -->
                                </div>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-primary">Tambah Data</button>
                                <a href="{{ route('feature') }}" class="btn btn-secondary ml-2">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

@endsection

@section('scripts')

@endsection

resources/views/pages/fitur_post.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Fitur Post
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Tambah Data Fitur</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Form Tambah Data Fitur</h4>
                    </div>
                    <div class="card-body">
                    <form action="{{ route('add_feature') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul</label>
                            <div class="col-sm-12 col-md-7">
                            <input type="text" name="title" id="title" placeholder="Judul" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi</label>
                            <div class="col-sm-12 col-md-7">
                            <textarea type="text" name="description" id="description" placeholder="Deskripsi" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Icon</label>
                            <div class="col-sm-12 col-md-7">
                                <div id="image-preview" class="image-preview">
                                    <label for="image-upload" id="image-label">Choose File</label>
                                    <input type="file" name="image" id="image" class="form-control-file" accept="image/png, image/jpeg">
                                    <!-- <input type="file" name="image" id="image"> -->
                                </div>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-primary">Tambah Data</button>
                                <a href="{{ route('feature') }}" class="btn btn-secondary ml-2">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

@endsection

@section('scripts')

@endsection

resources/views/pages/keunggulan.blade.php
@extends('layouts.master')

@section('title')
    Dashboard | Keunggulan
@endsection

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Data Keunggulan</h1>
    </div>
    <div class="section-body">
      <div class="row">
          <div class="col-md-12 col-lg-12">
              <div class="card">
                  <div class="card-header">
                    <a href="{{ route('form_advantage') }}" class="btn btn-primary my-4">
                      Tambah Keunggulan
                    </a>
                    <div class="card-header-form ml-auto">
                      <form method="get" action="{{ route('advantage') }}">
                        <div class="input-group">
                          <input type="text" class="form-control" name="search" placeholder="Search by title">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="card-body">
                      <table class="table table-hover table-striped table-bordered">                    
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Data Keunggulan
                          </button> -->
                      <!-- <table class="table table-striped">                     -->
                          <!-- <button type="button" class="btn btn-primary my-4" data-toggle="modal" data-target="#addModal">
                              Tambah Data Keunggulan
                          </button> -->
                          <!-- <table class="table table-hover table-striped table-bordered "> -->
                          <thead>
                              <tr>
                                  <th scope="col" class="text-center">No</th>
                                  <th scope="col" class="text-center">Judul</th>
                                  <th scope="col" class="text-center">Deskripsi</th>
                                  <th scope="col" class="text-center">Icon</th>
                                  <th scope="col" class="text-center">Action</th>
                              </tr>
                          </thead>
                          <tbody>
                          @foreach($advantage as $key=>$advan)
                          <tr>
                              <td class="text-center">{{$key+1}}</td>
                              <td class="text-center">{{$advan->title}}</td>
                              <td class="text-center">{{$advan->description}}</td>
                              <!-- <td class="text-center"><img src="{{URL::to('/storage/app/')}}{{$advan->image}}" style="width: 100px; height: 100px;"></td> -->
                              <!-- <td class="text-center"><img src="{{ url('/storage/app/'.$advan->image) }}" alt="" title=""></td> -->
                              <td class="text-center">
                                <?php $img_name = substr($advan->image, 13);?>
                                <img src="{{ asset('/storage/images').$img_name}}" alt="" title="" style="width: 100px; height: 100px;">
                              </td>
                              <td class="text-center">
                                  <a href="{{ route('edit_advantage', $advan->id) }}" class="btn btn-sm" data-id="{{$advan->id}}" data-title="{{$advan->title}}" data-description="{{$advan->description}}" data-image="{{$advan->image}}">
                                    <img src="{{ asset('/assets/img/icon/icon-edit.png') }}">
                                  </a>
                                  <button class="btn btn-sm" data-id="{{$advan->id}}" data-toggle="modal" data-target="#deleteModal">
                                    <img src="{{ asset('/assets/img/icon/icon-delete.png') }}">
                                  </button>
                              </td>
                          </tr>
                          @endforeach
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
      </div>
    </div>
</section>

<!-- Modal Edit Data -->
<div class="modal fade" id="editModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Data Admin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="edit_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
        {{csrf_field()}}
        {{method_field('put')}} <!-- cek change method -->
        <input type="hidden" name="id" id="id" value="">
            <div class="form-group">
            <label for="content">Judul</label>
                <input type="text" class="form-control" name="title" id="title" value="">
            </div>
            <div class="form-group">
            <label for="content">Deskripsi</label>
                <input type="text" class="form-control" name="description" id="description" value="">
            </div>
            <div class="form-group">
            <label for="content">Icon</label>
                <input type="file" class="form-control" name="image" id="image" class="form-control-file" value="">
            </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Edit Data</button>
        <button class="btn btn-secondary" type="submit" data-dismiss="modal">Cancel</button>
      </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal Delete Data -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-info" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="deleteModalLabel">Konfirmasi Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="delete_form" method="POST" action=""> <!-- set action attribte to empty, the url from js -->
                {{ csrf_field() }}
                {{ method_field('delete') }}
                <div class="modal-body">
                    <input type="hidden" name="id" value="" id="id">
                    <p class="text-area">
                        Apakah anda yakin akan menghapus data ini?
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Iya, Hapus </button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
  $('#editModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var admin_id = button.data('admin_id')
    var title = button.data('title')
    var description = button.data('description')
    var image = button.data('image')
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('advantage.update', '') }}/${id}`; // generate url
    $('#edit_form').attr('action', url); // set edit_form action attribute  

    modal.find('.modal-body #admin_id').val(admin_id);
    modal.find('.modal-body #title').val(title);
    modal.find('.modal-body #description').val(description);
    modal.find('.modal-body #image').val(image);
  })

  $('#deleteModal').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var modal = $(this)

    let url = `{{ route('advantage.destroy', '') }}/${id}`; // generate url
    $('#delete_form').attr('action', url); // set edit_form action attribute

    modal.find('.modal-body #id').val(id);
  })
</script>
@endsection